name: Check Public API
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - jb-main

permissions:
  contents: read

jobs:
  check-public-api:
    runs-on: macos-26-xlarge
    name: Check Public API
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Prerequisites
        uses: ./.github/actions/setup-prerequisites

      - name: Setup Xcode
        uses: ./.github/actions/setup-xcode

      - name: Check Public API
        run: |
          ./gradlew jbApiCheck \
            --no-daemon --stacktrace
